/*
 * Strava API v3
 *
 * Strava API
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package strava
// ActivityType : An enumeration of the types an activity may have.
type ActivityType string

// List of ActivityType
const (
	ALPINE_SKI ActivityType = "AlpineSki"
	BACKCOUNTRY_SKI ActivityType = "BackcountrySki"
	CANOEING ActivityType = "Canoeing"
	CROSSFIT ActivityType = "Crossfit"
	E_BIKE_RIDE ActivityType = "EBikeRide"
	ELLIPTICAL ActivityType = "Elliptical"
	HANDCYCLE ActivityType = "Handcycle"
	HIKE ActivityType = "Hike"
	ICE_SKATE ActivityType = "IceSkate"
	INLINE_SKATE ActivityType = "InlineSkate"
	KAYAKING ActivityType = "Kayaking"
	KITESURF ActivityType = "Kitesurf"
	NORDIC_SKI ActivityType = "NordicSki"
	RIDE ActivityType = "Ride"
	ROCK_CLIMBING ActivityType = "RockClimbing"
	ROLLER_SKI ActivityType = "RollerSki"
	ROWING ActivityType = "Rowing"
	RUN ActivityType = "Run"
	SNOWBOARD ActivityType = "Snowboard"
	SNOWSHOE ActivityType = "Snowshoe"
	STAIR_STEPPER ActivityType = "StairStepper"
	STAND_UP_PADDLING ActivityType = "StandUpPaddling"
	SURFING ActivityType = "Surfing"
	SWIM ActivityType = "Swim"
	VIRTUAL_RIDE ActivityType = "VirtualRide"
	VIRTUAL_RUN ActivityType = "VirtualRun"
	WALK ActivityType = "Walk"
	WEIGHT_TRAINING ActivityType = "WeightTraining"
	WHEELCHAIR ActivityType = "Wheelchair"
	WINDSURF ActivityType = "Windsurf"
	WORKOUT ActivityType = "Workout"
	YOGA ActivityType = "Yoga"
)
